package com.adminportal.controller;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;


import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import com.adminportal.domain.Book;
import com.adminportal.service.BookService;

@Controller
@RequestMapping("/book")
public class BookController {
	  
	@Autowired
	private BookService bookService;
	
	
	  //Same thing as @Requestmethod("/add")
	@RequestMapping(value="/add",method=RequestMethod.GET)
	public String addBook(Model model) {
		Book book = new Book();
		model.addAttribute("book", book);
		return "addBook";
				
	}

	@RequestMapping( value="/add", method=RequestMethod.POST)
	public String addBookPost(
	    	@ModelAttribute("book")	Book book, HttpServletRequest request) {
		
		
	//You have to persist the bok to the data base first before you can get an Id of the book.Since our Id is generated by Mysql data bse autogenerated format
		bookService.save(book);
		
	MultipartFile bookImage = book.getBookImage();
	     
	System.out.println("===================book Image" + bookImage);
	//Now let us convert the book to bytes of array
	
	try {
		byte[] bytes = bookImage.getBytes();
		
		String name= book.getId() +".png";
		
		System.out.println("================"+ name);
		
		//Buffered it out to your local system 
		BufferedOutputStream stream= new BufferedOutputStream(new FileOutputStream(new File("src/main/resources/static/image/book/" + name)));
		stream.write(bytes);
		stream.close();
	}catch(Exception e) {
		 e.printStackTrace();
	}
	
		
		return "redirect:bookList";
				
	}
	

	@RequestMapping("/updateBook")
	public String UpDateBookInfo(@RequestParam("id") Long id, Model model) {
	    
		Book book= bookService.findOne(id);
		model.addAttribute("book", book);
		
		return "updateBook";
		
	}
	
	@RequestMapping(value="/updateBook", method=RequestMethod.POST)
	public String updateBook(@ModelAttribute("book") Book book, HttpServletRequest request) {
		
		//Save the book to the data base first , this will hgelp to retrieve the Id of that particular book
		bookService.save(book);
		
		MultipartFile bookImage= book.getBookImage();
		
		if(! bookImage.isEmpty()) {
			try {
				
				byte[] bytes = bookImage.getBytes();
				String name= book.getId() + ".png";
				
				//To Update the existing image in the database or cloud Server, You have to first delete that existing image in the database.
				
				Files.delete(Paths.get("src/main/resources/static/image/book/" + name));
				
				//Now save the new one to the data base
				BufferedOutputStream stream= new BufferedOutputStream(
						new FileOutputStream(new File("src/main/resources/static/image/book/" + name)));
				stream.write(bytes);
				stream.close();
				
			}catch(Exception e) {
				e.printStackTrace();
			}
		}
		
		return "redirect:/book/bookInfo?id="+book.getId();
	}
	
	@RequestMapping("/bookInfo")
	public String bookInfo(@RequestParam("id") Long id, Model model) {
	    
		Book book= bookService.findOne(id);
		model.addAttribute("book", book);
		
		return "bookInfo";
		
	}
	
	@RequestMapping("/bookList")
	public String bookList(Model model) {
		List<Book> bookList= bookService.findAll();
		
		model.addAttribute("bookList",bookList);
		
		return "bookList";
	}
	
	@RequestMapping(value="remove",method= RequestMethod.POST)
	public String removeBook(
			@ModelAttribute("id") String id, Model model
			) {
		bookService.removeOne(Long.parseLong(id.substring(8))); //This means any other String apart from the first 8 characters
		List<Book> bookList =  bookService.findAll();
		model.addAttribute("bookList", bookList);
		
		return "redirect:/book/bookList";
	}
	
	
	
	
}
